// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcgzXkclcX1pcYDzFQECSTXFR06SVP7qc',
    appId: '1:67044253283:web:9d45aa46668894610f2256',
    messagingSenderId: '67044253283',
    projectId: 'monamienet-aquariustur',
    authDomain: 'monamienet-aquariustur.firebaseapp.com',
    storageBucket: 'monamienet-aquariustur.firebasestorage.app',
    measurementId: 'G-VR81CGLEK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-u5cI_cqeQkO03Ivo6MmO_nFmbMO8VXI',
    appId: '1:67044253283:android:ce06af448c8ba5ea0f2256',
    messagingSenderId: '67044253283',
    projectId: 'monamienet-aquariustur',
    storageBucket: 'monamienet-aquariustur.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdjLo8wBMngHdZmVq0SlUizQq34O1ajVc',
    appId: '1:67044253283:ios:a972499fe1ed1c580f2256',
    messagingSenderId: '67044253283',
    projectId: 'monamienet-aquariustur',
    storageBucket: 'monamienet-aquariustur.firebasestorage.app',
    androidClientId: '67044253283-j1duavtdhvr4bjgnt6f5d72lfh90priv.apps.googleusercontent.com',
    iosClientId: '67044253283-tcuftkgs0r84g0a1fue7gvqarg20fjse.apps.googleusercontent.com',
    iosBundleId: 'org.monamienet.aquariustur',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdjLo8wBMngHdZmVq0SlUizQq34O1ajVc',
    appId: '1:67044253283:ios:63d78e65e310a8000f2256',
    messagingSenderId: '67044253283',
    projectId: 'monamienet-aquariustur',
    storageBucket: 'monamienet-aquariustur.firebasestorage.app',
    androidClientId: '67044253283-j1duavtdhvr4bjgnt6f5d72lfh90priv.apps.googleusercontent.com',
    iosClientId: '67044253283-djpv2blu3r62plrhuqikg86fc5ce4qcn.apps.googleusercontent.com',
    iosBundleId: 'com.example.geotrackingStandalone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcgzXkclcX1pcYDzFQECSTXFR06SVP7qc',
    appId: '1:67044253283:web:bed4a92b2b48bacf0f2256',
    messagingSenderId: '67044253283',
    projectId: 'monamienet-aquariustur',
    authDomain: 'monamienet-aquariustur.firebaseapp.com',
    storageBucket: 'monamienet-aquariustur.firebasestorage.app',
    measurementId: 'G-0YJG5LG89G',
  );

}